<?php
require_once __DIR__ . '/bootstrap.php';
pos_require_operator();
require_once POS_APP_ROOT . '/includes/activity_flow.php';

$gateway = function_exists('pos_normalize_gateway')
    ? pos_normalize_gateway((string) ($_GET['gw'] ?? $_GET['gateway'] ?? ''))
    : strtolower(trim((string) ($_GET['gw'] ?? $_GET['gateway'] ?? '')));
$gatewayMeta = $gateway !== '' && function_exists('pos_gateway_meta') ? pos_gateway_meta($gateway) : null;
if (!$gateway || !$gatewayMeta || !pos_is_charge_processor($gateway) || !pos_gateway_is_live($gateway)) {
    http_response_code(422);
    exit('Choose an enabled payment gateway with ?gw=paypal, ?gw=nuvei, or another connected gateway.');
}
$csrf = generateCsrfToken();
$ar = isset($_COOKIE['di_parma_lang']) && $_COOKIE['di_parma_lang'] === 'ar';
?><!doctype html>
<html lang="<?=$ar ? 'ar' : 'en'?>" dir="<?=$ar ? 'rtl' : 'ltr'?>">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>DI PARMA | AUTH Capture</title>
<style>
:root{color-scheme:dark;--bg:#070b14;--card:#111a2b;--line:#263653;--gold:#ffd400;--green:#25d18a;--muted:#93a3bc;--red:#ff6b6b}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#18223b,#070b14 52%);color:#f7f9fc;font:15px Arial,sans-serif}.wrap{max-width:900px;margin:0 auto;padding:28px 18px}.head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:18px}.title{font-size:22px;font-weight:800;color:var(--gold)}.badge{border:1px solid var(--line);border-radius:8px;padding:8px 12px;color:var(--muted)}.panel{background:rgba(17,26,43,.94);border:1px solid var(--line);border-radius:12px;padding:18px;margin-bottom:16px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.hold{border:1px solid var(--line);border-radius:9px;padding:12px;background:#0b1322;cursor:pointer}.hold.active{border-color:var(--gold);box-shadow:0 0 0 1px var(--gold) inset}.hold strong{display:block;color:var(--gold);margin-bottom:7px}.muted{color:var(--muted);font-size:12px;line-height:1.6}.field{margin-top:14px}.field label{display:block;color:var(--muted);font-size:12px;margin-bottom:6px}.field input,.field select{width:100%;padding:11px;border:1px solid var(--line);border-radius:8px;background:#0b1322;color:#fff;font-size:16px}.choices{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.choices button,.submit{border:1px solid var(--line);border-radius:8px;background:#18243a;color:#fff;padding:10px 14px;cursor:pointer}.choices button.active{border-color:var(--gold);color:var(--gold)}.submit{width:100%;margin-top:16px;background:var(--gold);color:#111;font-weight:800;border:0}.submit:disabled{opacity:.5;cursor:not-allowed}.error{color:var(--red);margin-top:10px}.ok{color:var(--green);margin-top:10px}@media(max-width:650px){.grid{grid-template-columns:1fr}.head{display:block}.badge{display:inline-block;margin-top:10px}}
</style></head>
<body><main class="wrap">
<div class="head"><div class="title">AUTH Capture</div><div class="badge"><?=htmlspecialchars((string)($gatewayMeta['name'] ?? strtoupper($gateway)))?> · same gateway only</div></div>
<div class="panel"><div class="muted">Select an open AUTH hold from this gateway. Capture is sent to the original gateway and never to another provider.</div><div id="holds" class="grid" style="margin-top:14px"><div class="muted">Loading holds...</div></div></div>
<div class="panel" id="form" style="display:none"><div id="selected" class="muted"></div><div class="choices"><button type="button" data-mode="less">Less</button><button type="button" data-mode="same">Same</button><button type="button" data-mode="more">More</button></div><div class="field"><label for="captureAmount">Final capture amount</label><input id="captureAmount" type="number" min="0.01" step="0.01" inputmode="decimal"></div><div class="field"><label for="refundAmount">Refund amount (optional)</label><input id="refundAmount" type="number" min="0" step="0.01" value="0"></div><button id="submit" class="submit" type="button" disabled>Process Capture</button><div id="message"></div></div>
</main><script>
const CSRF=<?=json_encode($csrf)?>, GATEWAY=<?=json_encode($gateway)?>;let selected=null,mode='same';
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const money=n=>Number(n||0).toFixed(2);
function message(text,ok=false){const el=$('#message');el.className=ok?'ok':'error';el.textContent=text||''}
function setMode(next){mode=next;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(!selected)return;const input=$('#captureAmount');input.readOnly=mode==='same';input.value=mode==='same'?money(selected.amount):'';$('#submit').disabled=!(Number(input.value)>0)}
function render(rows){const box=$('#holds');if(!rows.length){box.innerHTML='<div class="muted">No open AUTH holds for this gateway.</div>';return}box.innerHTML=rows.map((h,i)=>`<button type="button" class="hold" data-i="${i}"><strong>${h.reference}</strong><span class="muted">${money(h.amount)} ${h.currency} · RRN ${h.rrn||'—'}<br>Approval ${h.gateway_approval||h.bank_approval||'—'}<br>Captured ${money(h.captured_total)} · Remaining ${money(h.remaining)}<br>Gateway ${h.gateway}${h.age_days!==null?`<br>Age ${h.age_days} day(s) · ${h.honor_period?'Honor period':(h.expired?'Expired':'Reauthorize window')}`:''}</span></button>`).join('');$$('.hold').forEach(b=>b.onclick=()=>selectHold(rows[Number(b.dataset.i)],b))}
function selectHold(h,el){selected=h;$$('.hold').forEach(x=>x.classList.remove('active'));el.classList.add('active');$('#form').style.display='';$('#selected').textContent=`${h.reference} · ${money(h.amount)} ${h.currency} · ${h.gateway}`+(h.expired?' · expired':'');setMode('same');$('#submit').disabled=!!h.expired;const old=$('#reauthorize');if(old)old.remove();if(h.can_reauthorize){const b=document.createElement('button');b.id='reauthorize';b.className='submit';b.style.background='#263653';b.style.color='#ffd400';b.textContent='Reauthorize PayPal for 3 more days';b.onclick=()=>reauthorize(h);$('#form').insertBefore(b,$('#submit'))}message(h.expired?'Authorization expired; capture is blocked.':'')}
async function reauthorize(h){const amount=Number($('#captureAmount').value||h.amount);message('Reauthorizing...',true);try{const r=await fetch('api/paypal_reauthorize.php',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({csrf_token:CSRF,reference:h.reference,authorization_id:h.payment_id,amount:amount,currency:h.currency})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Reauthorize failed');message('PayPal authorization renewed for 3 days.',true);await load()}catch(e){message(e.message||'Reauthorize failed')}}
async function load(){try{const r=await fetch('api/auth_holds.php?gateway='+encodeURIComponent(GATEWAY),{credentials:'same-origin'});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Could not load holds');render(d.holds||[])}catch(e){$('#holds').innerHTML='<div class="error">'+(e.message||'Could not load holds')+'</div>'}}
$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#captureAmount').oninput=()=>{$('#submit').disabled=!(Number($('#captureAmount').value)>0)};
$('#submit').onclick=async()=>{if(!selected)return;const amount=Number($('#captureAmount').value||0),refund=Number($('#refundAmount').value||0),hold=Number(selected.amount||0);if(amount<=0)return message('Enter the capture amount');if(mode==='less'&&amount>=hold)return message('Less capture must be below the hold amount');if(mode==='more'&&amount<=hold)return message('More capture must be above the hold amount');$('#submit').disabled=true;message('Processing...',true);try{const r=await fetch('api/transaction.php',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({csrf_token:CSRF,txn_type:'capture',gateway:GATEWAY,card_provider:GATEWAY,amount:amount,capture_amount:amount,refund_amount:refund,currency:selected.currency,orig_ref:selected.rrn,payment_id:selected.payment_id,transaction_id:selected.payment_id,rrn:selected.rrn,approval_code:selected.gateway_approval||selected.bank_approval,auth_code:selected.gateway_approval||selected.bank_approval,reference:selected.reference,settlement_target:'gateway',destination:'gateway',extra:{payment_id:selected.payment_id,linked_to_auth:true}})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Capture failed');message('Capture approved by '+GATEWAY+' · '+(d.reference||selected.reference),true);await load()}catch(e){message(e.message||'Capture failed')}finally{$('#submit').disabled=false}};load();
</script></body></html>
